<style>
    .lime {
        display: inline-block;
        position: relative;
        overflow: hidden;
        width: 80px;
        height: 80px;
        -moz-border-radius: 80px;
        border-radius: 80px;
        -webkit-border-radius: 80px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
    }
</style>
<?php
$i = 0;
?>

    <div class="row-fluid pull-left">
        <h2>Guia CASA SUL</h2>
        <p></p>
    </div>
    <div class="row-fluid">
        <center><h2><b>Soluções</b> para sua casa ou empresa!</h2></center>
    </div>
    <div class="row-fluid">
        <hr>
    </div>
        
    <div class="row-fluid">  
        <div class="span2">
            
        </div>
        <div class="span3">
            <?php for($i=0;$i<=9;$i++){?>
                <img src="<?php echo $this->dados[$i]['thumb'];?>" alt="<?php echo $this->dados[$i]['nome']?>" width="60px">
                <a href="<?php echo $this->url(array("controller"=>"guia","action"=>"show","id"=>$this->dados[$i]['idCategoria']),null,true)?>"><?php echo $this->dados[$i]['nome']?></a>
                <p></p>
            <?php }?>
        </div>
        <div class="span3">
            <?php for($i=10;$i<=19;$i++){?>
                <img src="<?php echo $this->dados[$i]['thumb'];?>" alt="<?php echo $this->dados[$i]['nome']?>" width="60px">
                <a href="<?php echo $this->url(array("controller"=>"guia","action"=>"show","id"=>$this->dados[$i]['idCategoria']),null,true)?>"><?php echo $this->dados[$i]['nome']?></a>
                <p></p>
            <?php }?>
        </div>
        <div class="span3">
            <?php for($i=20;$i<=29;$i++){?>
                <img src="<?php echo $this->dados[$i]['thumb'];?>" alt="<?php echo $this->dados[$i]['nome']?>"width="60px">
                <a href="<?php echo $this->url(array("controller"=>"guia","action"=>"show","id"=>$this->dados[$i]['idCategoria']),null,true)?>"><?php echo $this->dados[$i]['nome']?></a>
                <p></p>
            <?php }?>
        </div>
        <div class="span1">
            
        </div>
        </div>