<style>
    .lime {
        display: inline-block;
        position: relative;
        overflow: hidden;
        width: 80px;
        height: 80px;
        -moz-border-radius: 80px;
        border-radius: 80px;
        -webkit-border-radius: 80px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
    }
</style>
<?php 
$dbImagens = new Application_Model_DbTable_Imagens();
?>

<?php foreach($this->dados as $key => $guia):
    $imagem = $dbImagens->pesquisarImagem($guia['thumb']);
    ?>
    <center>
        <img class="lime" src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php echo $guia['titulo']?>">
        <h2><?php echo $guia['nome']?></h2>
    </center>
<?php
endforeach;
?>