<style>
    .lime {
        display: inline-block;
        position: relative;
        overflow: hidden;
        width: 150px;
        box-shadow: 2px 2px 2px #888888;
        /*-moz-border-radius: 80px;
        border-radius: 80px;
        -webkit-border-radius: 80px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
        */
    }
</style>

<div class="row-fluid pull-left">
        <h2><img src="/images/guia/guiaCasaSul.png"alt="Guia CasaSul"></h2>
        <p></p>
    </div>
    <div class="row-fluid ">
        <div class="span4 offset2">
            <h1><img src="<?php echo $this->logoGuia?>" width="45"><b><?php echo $this->tituloGuia ?></b></h1>
        </div>
        
    </div>
    <div class="row-fluid">
        <hr>
    </div>
        
    <div class="row-fluid offset2">  
        
            <center>
            <?php
                foreach ($this->dadosSponsor as $key => $sponsor) :
                    echo '<div class="span2">';
                    echo '<h1><b> <a href="'.$this->url(array("controller"=>"parceiro","action"=>"index","id"=>$sponsor['idPatrocinador']),null,true).'"><img class="lime" src="'.$sponsor['local'].$sponsor['logo'].'" ></h1></b>';
                    echo '</div>';
                endforeach;
            ?>
            </center>
    </div>

    <div class="row-fluid">
        <hr>
    </div>