<style type="text/css">
#conteudo {
	position: relative;
	width: 1514px;
	height: 1011px;
	z-index: 1;
	left: 10px;
	top: 8px;
	background-image: url(/images/background/espacoAnunciante.png);
        background-repeat: no-repeat;
}

#logoParceiro {
	position: absolute;
	width: 498px;
	height: 281px;
	z-index: 1;
	left: 444px;
	top: 68px;
}
#noticiaParceiro {
	position: absolute;
	width: 756px;
	height: 573px;
	z-index: 2;
	left: 696px;
	top: 402px;
}
#dadosParceiro {
	position: absolute;
	width: 369px;
	height: 167px;
	z-index: 3;
	left: 44px;
	top: 743px;
}
#logoParceiroDados {
	position: absolute;
	width: 200px;
	height: 115px;
	z-index: 1;
	left: 372px;
	top: -126px;
}
#cestaFrutas {
	position: absolute;
	width: 580px;
	height: 115px;
	z-index: 2;
	left: 21px;
	top: 179px;
	background-image: url(/images/background/cestaFrutas.png);
	background-repeat: no-repeat;
}
</style>
<?php #var_dump($this->dados);
$bdImagens = new Application_Model_DbTable_Imagens();
$logo = $bdImagens->pesquisarImagem($this->dados['logo']);?>
<div id="conteudo">
  <div id="logoParceiro">
      <center><img src="<?php echo $logo['local'].$logo['nome']?>"></center>
  </div>
  <div id="noticiaParceiro">
      NOTICIAS
  </div>
  <div id="dadosParceiro">
      <h1 style="color: #3e4095;"><?php echo $this->dados['nome']?></h1>
      <p><?php echo $this->dados['endereco']?></p>
      <?php if($this->dados['email']!= ''){
          echo '<p>'.$this->dados['email'].'</p>';
      }
      ?>
      <p><?php echo $this->dados['cep'].' - '.$this->dados['cidade'].' - '.$this->dados['estado']?></p>
      <p><?php echo $this->dados['telefone']?></p>
      <p><a href="<?php echo $this->dados['site']?>"><?php echo $this->dados['site']?></a></p>
    <div id="logoParceiroDados">
        <img src="<?php echo $logo['local'].$logo['nome']?>">
    </div>
    <div id="cestaFrutas"></div>
  </div>
</div>