<style type="text/css">
    @font-face{
    font-family: DejaVu;
    src: url(/fonts/DejaVuSans.ttf);
}
#conteudo {
	position: relative;
	width: 1514px;
	height: 1011px;
	z-index: 1;
	left: 10px;
	top: 8px;
	background-image: url(/images/background/espacoAnunciante.png);
        background-repeat: no-repeat;
}

#logoParceiro {
	position: absolute;
	width: 500px;
	height: 281px;
	z-index: 1;
	left: 444px;
	top: 68px;
}
#noticiaParceiro {
	position: absolute;
	width: 756px;
	height: 573px;
	z-index: 2;
	left: 696px;
	top: 402px;
}
#dadosParceiro {
	position: absolute;
	width: 369px;
	height: 167px;
	z-index: 3;
	left: 44px;
	top: 743px;
}
#logoParceiroDados {
	position: absolute;
	width: 200px;
	height: 115px;
	z-index: 1;
	left: 372px;
	top: -126px;
}
#cestaFrutas {
	position: absolute;
	width: 580px;
	height: 115px;
	z-index: 2;
	left: 30px;
	top: 175px;
	background-image: url(/images/background/cestaFrutas.png);
	background-repeat: no-repeat;
}

.textoParceiro{
    font-family: DejaVu;
}
p{
    padding-left: 20px;
}
h1{
    padding-left: 10px;
}

hr {
  border-top: 3px dotted #0098DA; 
  height: 1px;
  width:80%;
}
</style>
<?php #var_dump($this->dados);
$bdImagens = new Application_Model_DbTable_Imagens();
$logo = $bdImagens->pesquisarImagem($this->dados['logo']);?>
<div id="conteudo">
  <div id="logoParceiro">
      <img src="<?php echo $logo['local'].$logo['nome']?>" style="width:100%;max-height: 100%">
  </div>
  <div id="noticiaParceiro" style="font-family:Arial">
      <h1 style="color:#0098DA">
          Notícias <?php echo $this->dados['nome']?>
          <hr>
      </h1>
      <?php for($i=0;$i<=3;$i++){
          if(isset($this->noticias[$i])){
              #var_dump($this->noticias[$i]);
              echo '<h2 style="padding-left: 40px;color:#0098DA;font-family:Arial;"> '.$this->noticias[$i]['titulo'].'</h2><hr>';
              echo '<span style="padding-left: 40px;font-family:Arial;">'.$this->noticias[$i]['descricao'].'</span>';
              echo '<p></p>';
              ?>
                <div style="width:80%;word-wrap: break-word;text-align:justify;text-justify:inter-word;font-family: Arial;font-size: 130%;padding-left: 40px;">
                    <?php echo $this->noticias[$i]['texto']?>
                </div>
      <?php
          }
      }?>
  </div>
  <div id="dadosParceiro">
      <h1  style="color: #3e4095;font-family: DejaVu"><?php echo $this->dados['nome']?></h1>
      <h1  style="color: #3e4095;font-family: DejaVu">Portobello S.A.</h1>
      <p id="textoParceiro"><?php echo $this->dados['endereco']?></p>
      <?php if($this->dados['email']!= ''){
          echo '<p>'.$this->dados['email'].'</p>';
      }
      ?>
      <p id="textoParceiro"><?php echo $this->dados['cep'].' - '.$this->dados['cidade'].' - '.$this->dados['estado']?></p>
      <p id="textoParceiro"><?php echo $this->dados['telefone']?></p>
      <p id="textoParceiro"><a href="<?php echo $this->dados['site']?>"><?php echo $this->dados['site']?></a></p>
    <div id="logoParceiroDados" >
        <img src="<?php echo $logo['local'].$logo['nome']?>" style="min-width: 30px;max-width: 200px;">
    </div>
    <div id="cestaFrutas"></div>
  </div>
</div>