<div id="page-bottom" class="clearfix">
    	<div class="wrapper clearfix" id="bottom-sidebar">
        
        	<aside class="widget one-third">
            
            	<h2 class="widget-title">Editora</h2>
                <hr class="barra-rodape">
                    <p><a href="" class="link-branco">Web-mail</a></p>
                    <p><a href="" class="link-branco">Quem somos</a></p>
                    <p>&nbsp;</p>

                
                <h2 class="widget-title">Revista</h2>
                <hr class="barra-rodape">
                    <p><a href="" class="link-branco">Edição atual</a></p>
                    <p><a href="" class="link-branco">Edição anteriores</a></p>
                    <p><a href="" class="link-branco">Assinaturas</a></p>
                    <p>&nbsp;</p>
                
                
                
                <h2 class="widget-title">Programa</h2>
                <hr class="barra-rodape">
                    <p><a href="" class="link-branco">Edição atual</a></p>
                    <p><a href="" class="link-branco">Edição anteriores</a></p>                       
            </aside><!--one-third-->
            
            
            
            <aside class="widget one-third">
            	<h2 class="widget-title">Newsletter</h2>
                <form action="" method="post" id="form-newsletter">
                    <p><input type='text' class='campo-newsletter' name="nome-newsletter" id="nome-newsletter" placeholder="Nome"></p>
                    <p><input type='text' class='campo-newsletter' name="email-newsletter" id="email-newsletter" placeholder="E-mail"></p>
                    <p><input name="enviar-newsletter" id="enviar-newsletter" type="submit" value="Enviar"></p>
                </form>
                
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                
                <div class="img_ribeiro">
                    <img src="placeholders/ribeiro_de_campos.png" alt="Ribeiro de campos">
                    <p>&nbsp;</p>
                    <p><a href="">GUIA CASA SUL</a></p>
                    <p><a href="">EVENTOS</a></p>
                </div>
  
            </aside><!--one-third-->
            
            
            
            <aside class="widget one-third last">
            	<h2 class="widget-title">Curtir</h2>
                <div id="fb-root"></div>
				<script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                
                <div class="limitarbox">
                    <div class="fb-like-box" data-href="http://www.facebook.com/estiloCasaSul" data-width="350" data-height="510" data-show-faces="true" 
                    data-colorscheme="light" data-stream="false" data-header="false" data-border-color="#FFF"></div>
                </div>

            </aside><!--one-third-->
            
            
            
            <div class="clear"></div>
        </div><!--bottom-sidebar-->
        
        <footer id="footer" class="clearfix">
        	<div id="footer-inner">
            	<div class="wrapper">
            		<p id="copyrights">Desenvolvido por <a href="http://www.opisystem.com.br" class="link-branco" target="_blank"> OPI System</a> &copy; 2013 | Todos os direitos reservados.</p>
                    <ul class="social-links clearfix">
                    
                        <li class="facebook-icon">
                            <a target="_blank" title="Facebook" class="facebook" href="#"><img src="images/icons/facebook-icon.png" alt="" /></a>
                        </li>

                        <li class="twitter-icon">
                            <a target="_blank" title="Twitter" class="twitter" href="#"><img src="images/icons/twitter-icon.png" alt="" /></a>
                        </li>
                        
                        <li class="rss-icon">
                            <a target="_blank" title="RSS" href="#"><img src="images/icons/rss-icon.png" alt="" /></a>
                        </li>

                    </ul><!--social-links-->
                    <div class="clear"></div>
                </div>
            </div><!--footer-inner-->
        </footer>
