<!DOCTYPE HTML>
<html lang="pt-br" itemscope itemtype="http://schema.org/Organization">
<head>
<meta charset="utf-8">

<meta name="description" content="">

<meta name="keywords" content="">

<meta name="author" content="OPISystem">
<meta name="revisit-after" content="3 days">
<meta name="robots" content="index, follow">

<title>CasaSul</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/css/reset.css" rel="stylesheet">
<link rel="stylesheet" href="/css/prettyPhoto.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/flexslider.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/sequencejs-theme.apple-style.css" type="text/css" media="screen" />
<link href="/css/style.css" rel="stylesheet">
<link href="/css/responsive.css" rel="stylesheet">
<link rel="stylesheet" href="/css/themes/default/default.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/nivo-slider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/shadowbox/shadowbox.css" />
<link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if IE 7]><link rel="stylesheet" href="css/ie7.css" type="text/css" media="all" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="css/ie8.css" type="text/css" media="all" /><![endif]-->
<!--[if IE ]><link rel="stylesheet" href="css/ie.css" type="text/css" media="all" /><![endif]-->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<!-- Le fav and touch icons -->
<link rel="shortcut icon" href="img/favicon.html">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114.png">

<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/jflickrfeed.min.js"></script>
<script type="text/javascript" src="js/jquery.carouFredSel-5.6.4-packed.js" charset="utf-8"></script>
<script type="text/javascript" src="/js/jquery.tweet.js"></script>
<script type="text/javascript" src="/js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="/js/jquery.flexslider.js"></script>
<script type="text/javascript" src="/js/sequence.jquery-min.js"></script>
<script type="text/javascript" src="/js/jquery.masonry.min.js"></script>
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/js/jquery.form.js"></script>
<script src="/js/custom.js" charset="utf-8"></script>
<script type="text/javascript" src="/shadowbox/shadowbox.js"></script>
<script type="text/javascript">
//FUNÇÃO PARA SHADOWBOX
Shadowbox.init({
language: 'pt',
player: ['img', 'html', 'swf']
});
</script>

</head>
<body class="home">		
	
    <?php echo $this->render('slider.phtml') ?>	
    <?php echo $this->render('header.phtml') ?>
	<?php echo $this->layout()->content; ?>	
    <?php echo $this->render('footer.phtml') ?>
        
        
    </div><!--page-bottom-->
 <script type="text/javascript" src="/js/jquery.nivo.slider.js"></script>   
 <script type="text/javascript">
    $(window).load(function() {
      $('#slider').nivoSlider();
   });
 </script>   
</body>
</html>

