<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<!DOCTYPE html>
<html lang="pt-Br">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=iso" />
<title>CASA SUL - O Estilo de Vida da Região Sul</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/reset.css')?>
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/prettyPhoto.css')?>
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/flexslider.css')?>
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/sequencejs-theme.apple-style.css')?>
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/style.css')?>
<?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./css/responsive.css')?>
<link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if IE 7]><link rel="stylesheet" href="css/ie7.css" type="text/css" media="all" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="css/ie8.css" type="text/css" media="all" /><![endif]-->
<!--[if IE ]><link rel="stylesheet" href="css/ie.css" type="text/css" media="all" /><![endif]-->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<!-- Le fav and touch icons -->
<link rel="shortcut icon" href="img/favicon.html">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114.png">

<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jflickrfeed.min.js"></script>
<script src="<?php echo $baseUrl?>/js/jquery.carouFredSel-5.6.4-packed.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.tweet.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.flexslider.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/sequence.jquery-min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.masonry.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.form.js"></script>
<script src="<?php echo $baseUrl?>/js/custom.js" charset="utf-8"></script>

</head>
<body class="home">	
    <?php echo $this->render('slider.phtml') ?>	
    <?php echo $this->render('header.phtml') ?>
	<?php echo $this->layout()->content; ?>	
    <?php echo $this->render('footer.phtml') ?>
</body>
</html>