<?php
    $dbImagens = new Application_Model_DbTable_Imagens();
    $where = 'categoria = 4';
    $dadosImagens = $dbImagens->pesquisarImagem(null, $where);
?>

<section id="slider-wrapper">
        <div id="main-slider">               
            <div class="wave-bg">
				
                <div id="banner_topo">
                    <div class="slider-wrapper theme-default">
                        <div id="slider" class="nivoSlider">
                            <?php foreach ($dadosImagens as $key => $imagem):?>
                            <img src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php ucfirst($imagem['nome'])?>" title="<?php ucfirst($imagem['nome'])?>" />
                            <?php endforeach ?>

                        </div>
                        
                        <div id="htmlcaption1" class="nivo-html-caption">
                            
                        </div>
                        
                        <div id="htmlcaption2" class="nivo-html-caption">
                            
                        </div> 
                        
                        <div id="htmlcaption3" class="nivo-html-caption">
                            
                        </div> 
                        
                    </div>
                </div>
                
                
                
            </div><!--wave-bg-->
            <span id="slider-corner">&nbsp;</span>
        </div><!--main-slider-->
    </section><!--slider-wrapper-->
