    <section id="slider-wrapper">
        <div id="main-slider">               
            <div class="wave-bg">
				<div id="sequence-wrapper">
                    <div id="sequence">
                        <ul>
                            <li class="animate-in" style="text-align: center;">
                                <img src="placeholders/slider1.jpg" alt="" />
                            </li>
                        </ul>
                    </div><!--sequence-->
                    <div class="controls">
                        <span class="prev"></span>
                        <span class="next"></span>
                    </div><!--controls-->
                </div><!--sequence-wrapper-->
            </div><!--wave-bg-->
            <span id="slider-corner">&nbsp;</span>
        </div><!--main-slider-->
    </section><!--slider-wrapper-->