<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>

<style>
    img.center {        
        position: absolute;
        margin: auto;
        left: 0; 
        right: 0;
        top: 0;
        bottom: 0;  
    }
</style>

<?php
    $dbImagens = new Application_Model_DbTable_Imagens();
    $where = 'categoria = 4';
    $dadosImagens = $dbImagens->pesquisarImagem(null, $where);
?>

<section id="slider-wrapper">
        <div id="main-slider">               
            <div class="wave-bg">
				<div id="sequence-wrapper">
                    <div id="sequence">
                        <ul>
                            <!--<li class="animate-in" style="text-align: center;">
                                <img src="placeholders/slider1.jpg" alt="" />
                            </li>-->
                            <?php foreach ($dadosImagens as $key => $imagem):?>
                                <li class="animate-in" style="text-align: center;">
                                    <img class='center' src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php ucfirst($imagem['nome'])?>" /></a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    </div><!--sequence-->
                    <div class="controls">
                        <span class="prev"></span>
                        <span class="next"></span>
                    </div><!--controls-->
                </div><!--sequence-wrapper-->
            </div><!--wave-bg-->
            <span id="slider-corner">&nbsp;</span>
        </div><!--main-slider-->
    </section><!--slider-wrapper-->