<?php #var_dump($this->dados)?>

<head>
    <style>
        hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 1px solid #ccc;
            margin: 1em 0;
            padding: 0;
        }
    </style>
</head>
<body>
    
<center>
    <?php foreach($this->dados AS $key => $programa):?>
        <h1><b><?php echo ucfirst($programa['titulo']);?></b></h1>
        <p><small>Data de publicação: <?php echo $programa['dtInclusao'];?></small>
        <h3>Descrição: <?php echo $programa['descricao'];?></h3>
        <br>
        <iframe width="560" height="315" src="http://www.youtube.com/embed/<?php echo $programa['url'];?>?rel=0" frameborder="0" allowfullscreen></iframe>
        <hr>
    <?php endforeach;?>
    
</center>
</body>