<?php #var_dump($this->dados)?>

<head>
    <style>
        hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 1px solid #ccc;
            margin: 1em 0;
            padding: 0;
        }
    </style>
</head>
<body>
    
<center>
    <?php foreach($this->dados AS $key => $programa):?>
        <h1><b><?php echo ucfirst($programa['titulo']);?></b></h1>
        <h3><?php echo $programa['descricao'];?></h3>
        <small>Data de publicação: <?php echo $programa['dtInclusao'];?></small>
        <iframe width="640" height="360" src="<?php #echo $programa['url'];?>" frameborder="0" allowfullscreen></iframe>    
        <hr>
    <?php endforeach;?>
    
</center>
</body>