<?php
function custom_echo($str)
{
  if(strlen($str)<=150)
  {
    return $str;
  }
  else
  {
    $y=substr($str,0,150) .' ' .'<span class="entry-meta"></span><a href="#" class="entry-author"> continuar lendo&nbsp;...</a>';
    return $y;
  }
}?>
<style>
    .lime {
        display: inline-block;
        position: relative;
        overflow: hidden;
        width: 80px;
        height: 80px;
        -moz-border-radius: 80px;
        border-radius: 80px;
        -webkit-border-radius: 80px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
    }
</style>

<?php 
$dbImagens = new Application_Model_DbTable_Imagens();
?>
    <div class="main-content clearfix">
    	<div id="left-corner"></div>
        <div class="wrapper">
            <section class="kopa-widget">
            	<div class="kopa-widget-left">
                	<h3 class="widget-title">Revista CasaSUL</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <?php for($i=0;$i<=3;$i++):
                            if( ($i == 0) AND (!is_null( $this->dadosNoticias[$i] ) ) ){
                                $thumbNoticia = $dbImagens->pesquisarImagem( $this->dadosNoticias[$i]['thumb'] );
                                ?>
                                <article class="entry-item">
                                    <a class="k-featured-img border-img" href="#"><img src="<?php echo $thumbNoticia['local'].$thumbNoticia['nome'];?>" class="responsive-img scale-hover" alt="" /></a>
                                        <div class="entry-content">
                                            <span class="entry-date"><?php echo $this->dadosNoticias[$i]['dtInclusao']?></span>
                                            <span class="entry-meta">por&nbsp;</span><a href="#" class="entry-author"><?php $this->dadosNoticias[$i]['autor']?></a>
                                            <span class="entry-meta">, in&nbsp;</span><a class="entry-categories" href="#">Motion</a>
                                            <span class="entry-meta">, 28&nbsp;</span><a class="entry-comment" href="#">Comments</a>
                                            <h2 class="entry-title"><a href="#"><?php echo $this->dadosNoticias[$i]['titulo']?></a></h2>
                                            <p><?php echo custom_echo( $this->dadosNoticias[$i]['texto'] )?></p>
                                        </div><!--entry-content-->
                                </article><!--entry-item-->
                            <?php }elseif ( ($i!=0) AND ( !is_null( $this->dadosNoticias[$i] ) ) ) { ?>
                                        <li>
                                            <article>
                                                <h6 class="entry-title"><a href="#"><?php echo $this->dadosNoticias[$i]['titulo']?></a></h6>
                                                <span class="entry-meta">Update:&nbsp;</span>
                                                <span class="entry-date"><?php echo $this->dadosNoticias[$i]['dtInclusao']?></span>
                                                <span class="entry-meta">&nbsp;&nbsp;by&nbsp;</span>
                                                <a href="#" class="entry-author">Admin</a>
                                                <p><?php echo custom_echo( $this->dadosNoticias[$i]['texto'] )?></p>
                                            </article>
                                        </li>
                                    <?php }else{
                                        $i++;
                                    }
                    endfor;?>

                    
                    <!-- <ul class="older-posts">
                    </ul><!--older-posts-->
                    <div class="clear"></div>
                    
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
        
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Patrocinadores</h3>
                </div><!--kopa-widget-left-->
                
                <!-- Patrocinadores-->
                
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            
                            <?php for($i=0;$i<=3;$i++):
                                if ( is_null( $this->dadosImagens[$i]['nome'] )):
                                    $i++;break;
                                endif;?>
                                <li>
                                    <article>
                                        <div class="article-thumb border-img">                                        
                                            <a class="video-icon hover-effect" href="#" rel="prettyPhoto"><img class="responsive-img" src="<?php echo $this->dadosImagens[$i]['local'].$this->dadosImagens[$i]['nome'];?>" alt="<?php ucfirst($this->dadosImagens[$i]['nome'])?>" /></a>
                                        </div><!--article-thumb-->
                                        <a class="entry-title" href="#"><?php echo $this->dadosImagens[$i]['descricao']?></a>
                                        <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                    </article>
                                </li>
                                
                            <?php endfor;?>

                        </ul><!--end:Patrocinadores-->
                        
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Noticias</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            
                           <!-- Notícias-->
                
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            
                            <?php foreach($this->dadosNoticias as $key => $noticia):?>
                            <?php $imgNoticia = $dbImagens->pesquisarImagem($noticia['thumb']);?>
                                <li>
                                    <article>
                                        <div class="article-thumb border-img">                                        
                                            <a class="video-icon hover-effect" href="<?php echo $this->url(array("controller"=>"noticias","action"=>"show","id"=>$noticia['idMateria']),null,true)?>" rel="prettyPhoto"><img class="responsive-img" src="<?php echo $imgNoticia['local'].$imgNoticia['nome'];?>" alt="<?php ucfirst($this->noticia['titulo'])?>" /></a>
                                        </div><!--article-thumb-->
                                        <a class="entry-title" href="#"><?php echo $noticia['titulo']?></a>
                                        <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                    </article>
                                </li>
                            <?php endforeach;?>

                        </ul><!--end:Notícias-->
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
        
            <section class="kopa-widget">
            	<div class="kopa-widget-left">
                	<h3 class="widget-title">Guia CasaSUL</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                    	<?php foreach ($this->dadosGuias as $key => $guia) :?>
                        <?php #var_dump($this->dadosGuias)?>
                        <article class="one-fifth feature-service clearfix">
                            <div class="lime">
                                <a class="kopacms-icon-hover" href="#">
                                    <img class="hover-icon" src="<?php echo $guia['local'].$guia['nome']?>" alt="<?php echo $guia['categoria']?>" width="80px" height="80px">
                                    <img class="cms-icon" src="<?php echo $guia['local'].$guia['nome']?>" alt="<?php echo $guia['categoria']?>" width="80px" height="80px">
                                </a>                        
                            </div>
                            <h6 class="entry-title"><a href="<?php echo $this->url(array("controller"=>"guia","categoria"=>$guia['idCategoria']),null,true)?>"><?php echo $guia['categoria']?></a></h6>
                            <p><?php echo $guia['descCat']?></p>
                        </article>
                        <?php endforeach;?>
                    </div>
                    <div class="clear"></div>
                </div><!--main-col-->
                <div class="clear"></div>
				
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Programa</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            
                            <!-- 
                            
                                Fazer um foreach, que exibe os 4 ultimos programas (videos)
                            
                                foreach( $this->programas as $key => $programa ){
                                
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-1.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                            <!--
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            }
                            -->
                            <?php for($i=0;$i<=3;$i++):
                                if ( is_null( $this->dadosProgramas[$i]['url'] )):
                                    $i++;break;
                                endif;?>
                                <li>
                                    <article>
                                        <div class="article-thumb border-img" >
                                            <iframe width="300" height="315" src="http://www.youtube.com/embed/<?php echo $this->dadosProgramas[$i]['url'];?>?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
                                            <a class="entry-title" href="<?php echo $this->url(array("controller"=>"programa","action"=>"index",'video'=>$this->dadosProgramas[$i]['idPrograma']),null,true)?>"><?php echo ucwords( $this->dadosProgramas[$i]['titulo'] )?></a>
                                            <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                        </div>
                                    </article>
                                </li>
                                
                            <?php endfor;?>        
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
			
        </div><!--wrapper-->
    </div><!--main-content-->
    
    <script>// By Chris Coyier & tweaked by Mathias Bynens

$(function() {

	// Find all YouTube videos
	var $allVideos = $("iframe[src^='http://www.youtube.com']"),

	    // The element that is fluid width
	    $fluidEl = $("iframe");

	// Figure out and save aspect ratio for each video
	$allVideos.each(function() {

		$(this)
			.data('aspectRatio', this.height / this.width)
			
			// and remove the hard coded width/height
			.removeAttr('height')
			.removeAttr('width');

	});

	// When the window is resized
	// (You'll probably want to debounce this)
	$(window).resize(function() {

		var newWidth = $fluidEl.width();
		
		// Resize all videos according to their own aspect ratio
		$allVideos.each(function() {

			var $el = $(this);
			$el
				.width(newWidth)
				.height(newWidth * $el.data('aspectRatio'));

		});

	// Kick off one resize to fix all videos on page load
	}).resize();

});</script>