
    <div class="main-content clearfix">
    	<div id="left-corner"></div>
        <div class="wrapper">
            <section class="kopa-widget">
            	<div class="kopa-widget-left">
                	<h3 class="widget-title">Revista CasaSUL</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                	<article class="entry-item">
                    	<a class="k-featured-img border-img" href="#"><img src="placeholders/535x220/535x220-1.png" class="responsive-img scale-hover" alt="" /></a>
                        <div class="entry-content">
                        	<span class="entry-date">08 Nov 2012</span>
                            <span class="entry-meta">by&nbsp;</span><a href="#" class="entry-author">Admin</a>
                            <span class="entry-meta">, in&nbsp;</span><a class="entry-categories" href="#">Motion</a>
                            <span class="entry-meta">, 28&nbsp;</span><a class="entry-comment" href="#">Comments</a>
                            <h2 class="entry-title"><a href="#">Girl in white dress running in a field</a></h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div><!--entry-content-->
                    </article><!--entry-item-->
                    <ul class="older-posts">
                    	<li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">Girl in white dress running in a field</a></h6>
                                <span class="entry-meta">Update:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;by&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                        <li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">Girl in white dress running in a field</a></h6>
                                <span class="entry-meta">Update:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;by&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                        <li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">Girl in white dress running in a field</a></h6>
                                <span class="entry-meta">Update:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;by&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                    </ul><!--older-posts-->
                    <div class="clear"></div>
                    
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
        
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Patrocinadores</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-1.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-2.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-2.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-4.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-4.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-3.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                </article>
                            </li>
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Noticias</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-1.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-2.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-2.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-4.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-4.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-3.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
        
            <section class="kopa-widget">
            	<div class="kopa-widget-left">
                	<h3 class="widget-title">Guia CasaSUL</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                    	<article class="one-fifth feature-service clearfix">
                        	<a class="kopacms-icon-hover" href="#">
                            	<img class="hover-icon" src="images/icons/theme-design-icon.png" alt="Theme design">
                                <img class="cms-icon" src="images/icons/theme-design-icon-hover.png" alt="Theme design">
                            </a>
                            <h6 class="entry-title"><a href="#">Theme design</a></h6>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi.</p>
                        </article><!--one-fifth-->
                        <article class="one-fifth feature-service clearfix">
                        	<a class="kopacms-icon-hover" href="#">
                            	<img class="hover-icon" src="images/icons/mobile-app-icon.png" alt="Theme design">
                                <img class="cms-icon" src="images/icons/mobile-app-icon-hover.png" alt="Theme design">
                            </a>                        
                            <h6 class="entry-title"><a href="#">Mobile APPs</a></h6>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi.</p>
                        </article><!--one-fifth-->
                        <article class="one-fifth feature-service clearfix">
                        	<a class="kopacms-icon-hover" href="#">
                            	<img class="hover-icon" src="images/icons/cartoons-icon.png" alt="Theme design">
                                <img class="cms-icon" src="images/icons/cartoons-icon-hover.png" alt="Theme design">
                            </a>                        
                            <h6 class="entry-title"><a href="#">Production Cartoons</a></h6>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi.</p>
                        </article><!--one-fifth-->
                        <article class="one-fifth feature-service clearfix">
                        	<a class="kopacms-icon-hover" href="#">
                            	<img class="hover-icon" src="images/icons/entertainment-icon.png" alt="Theme design">
                                <img class="cms-icon" src="images/icons/entertainment-icon-hover.png" alt="Theme design">
                            </a>                        
                            <h6 class="entry-title"><a href="#">Entertainments</a></h6>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi.</p>
                        </article><!--one-fifth-->
                        <article class="one-fifth feature-service clearfix last">
                        	<a class="kopacms-icon-hover" href="#">
                            	<img class="hover-icon" src="images/icons/travel-icon.png" alt="Theme design">
                                <img class="cms-icon" src="images/icons/travel-icon-hover.png" alt="Theme design">
                            </a>                        
                            <h6 class="entry-title"><a href="#">Travel</a></h6>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi.</p>
                        </article><!--one-fifth-->
                    </div>
                    <div class="clear"></div>
                </div><!--main-col-->
                <div class="clear"></div>
				
            </section><!--kopa-widget-->
            <div class="divider"></div>
            
            <section class="kopa-widget kp-carousel">
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Programa</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            
                            <!-- 
                            
                                Fazer um foreach, que exibe os 4 ultimos programas (videos)
                            
                                foreach( $this->programas as $key => $programa ){
                                
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-1.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                            <!--
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            }
                            -->
                            <?php for($i=0;$i<=3;$i++):?>
                                <li>
                                    <article>
                                        <div class="article-thumb border-img">
                                            <iframe width="300" height="315" src="http://www.youtube.com/embed/<?php echo $this->dadosProgramas[$i]['url'];?>?rel=0" frameborder="0" allowfullscreen></iframe>
                                        </div>
                                    </article>
                                </li>
                                
                            <?php endfor;?>        
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-1.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-2.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-2.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="video-icon hover-effect" href="http://vimeo.com/46163823" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-4.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-4.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href="placeholders/205x144/205x144-3.jpg" rel="prettyPhoto"><img class="responsive-img" src="placeholders/205x144/205x144-3.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Global child mortality declines</a>
                                    <span class="entry-meta">in&nbsp;</span><a class="entry-categories" href="#">Photoshop,</a>&nbsp;<a class="entry-categories" href="#">illustrator</a>
                                </article>
                            </li>
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                </div><!--main-col-->
                <div class="clear"></div>
            </section><!--kopa-widget-->
            <div class="divider"></div>
			
        </div><!--wrapper-->
    </div><!--main-content-->