<?php
function custom_echo($str)
{
  if(strlen($str)<=150)
  {
    return $str;
  }
  else
  {
    $y=substr($str,0,150) .' ' .'<span class="entry-meta"></span><a href="#" class="entry-author"> continuar lendo&nbsp;...</a>';
    return $y;
  }
}?>

<div class="main-content clearfix">
    	<div id="left-corner"></div>
        <div class="wrapper">

			<section class="kopa-widget kp-carousel">
            
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Editorial</h3>
                    <a href="#" class="view-all">Veja nossa revista</a>
                </div><!--kopa-widget-left-->
                
                <div class="main-col">
                
                    <div class="list-carousel responsive">
                        <ul class="recent-works clearfix">
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="placeholders/205x144/imag01.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Dicas para tornar suas salas ambientais agradáveis</a>
                                    <p class="descr"> Quando os ambientes estão
                                integrados, a dica é escolher
                                o mesmo estilo em todas as
                                ambientações, observando as
                                cores e revestimentos com 
                                paleta de cores. Em uma sala
                                deve compor sofás e poltronas
                                confortáveis e uma mesa de 
                                centro...</p>
                                   
                                </article>
                               
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="placeholders/205x144/imag02.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Tudo sobre como decorar seu quarto de solteiro</a>
                                    <p class="descr">Quando os ambientes estão
                                integrados, a dica é escolher
                                o mesmo estilo em todas as
                                ambientações, observando as
                                cores e revestimentos com 
                                paleta de cores. Em uma sala
                                deve compor sofás e poltronas
                                confortáveis e uma mesa de 
                                centro...</p>
                                   
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="placeholders/205x144/imag03.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Descubra o diferencial na iluminação de ambientes</a>
                                    <p class="descr">Quando os ambientes estão
                                integrados, a dica é escolher
                                o mesmo estilo em todas as
                                ambientações, observando as
                                cores e revestimentos com 
                                paleta de cores. Em uma sala
                                deve compor sofás e poltronas
                                confortáveis e uma mesa de 
                                centro...</p>
                                    
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="placeholders/205x144/imag04.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Ambientes sofisticados com sensibilidade e estética</a>
                                    <p class="descr">Quando os ambientes estão
                                integrados, a dica é escolher
                                o mesmo estilo em todas as
                                ambientações, observando as
                                cores e revestimentos com 
                                paleta de cores. Em uma sala
                                deve compor sofás e poltronas
                                confortáveis e uma mesa de 
                                centro...</p>
                                    
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="placeholders/205x144/imag01.jpg" alt="" /></a>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#">Descubra o diferencial na iluminação de ambientes</a>
                                    <p class="descr">Quando os ambientes estão
                                integrados, a dica é escolher
                                o mesmo estilo em todas as
                                ambientações, observando as
                                cores e revestimentos com 
                                paleta de cores. Em uma sala
                                deve compor sofás e poltronas
                                confortáveis e uma mesa de 
                                centro...</p>
                                  
                                </article>
                            </li>
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-1" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-1" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                    <div class="divider"></div>
                </div><!--main-col-->
                
                
                
                <div class="clear"></div>
            </section><!--kopa-widget-->
            
            
            
            <section class="kopa-widget kp-carousel">
            
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Destaque</h3>
                </div><!--kopa-widget-left-->
                
                <div class="main-col">
                
                    <div class="list-carousel responsive">
                        <ul class="recent-works2 clearfix">
                            <?php 
$dbImagens = new Application_Model_DbTable_Imagens();
$dbUsuario = new Admin_Model_DbTable_Usuario();
#'categoria = 1'
$dadosImagens = $dbImagens->pesquisarImagem(null);

			foreach ($this->dadosImagens as $key => $imagem):
?>
			<li>
                                 <article>
                                    <div class="article-thumb border-img">                                        
                                        <a class="zoom-icon hover-effect" href=""><img class="responsive-img" src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php ucfirst($imagem['nome'])?>" /></a>
                                    </div><!--article-thumb-->

                                </article>
                            </li>
<?php endforeach;?>

                            
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-2" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-2" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                    <div class="divider"></div>
                </div><!--main-col-->
                
                
                
                <div class="clear"></div>
            </section><!--kopa-widget-->
            
            
            

            
            <section class="kopa-widget">
            	<div class="kopa-widget-left">
                	<h3 class="widget-title">Notícias</h3>
                </div><!--kopa-widget-left-->
                <div class="main-col">
                	<article class="entry-item">
                    	<a class="k-featured-img border-img" href="#"><img src="placeholders/535x220/535x220-1.png" class="responsive-img scale-hover" alt="" /></a>
                        <div class="entry-content">
                        	<span class="entry-date">08 Nov 2012</span>
                            <span class="entry-meta">por&nbsp;</span><a href="#" class="entry-author">Admin</a>
                            <span class="entry-meta">, em&nbsp;</span><a class="entry-categories" href="#">Eventos</a>
                            <span class="entry-meta">, 28&nbsp;</span><a class="entry-comment" href="#">Comentarios</a>
                            <h2 class="entry-title"><a href="#">Design Awards 2014</a></h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div><!--entry-content-->
                    </article><!--entry-item-->
                    <ul class="older-posts">
                    	<li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">Para inspirar!</a></h6>
                                <span class="entry-meta">Postado:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;por&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                        <li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">Hight Lights</a></h6>
                                <span class="entry-meta">Postado:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;por&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                        <li>
                        	<article>
                            	<h6 class="entry-title"><a href="#">A sala de Estar</a></h6>
                                <span class="entry-meta">Postado:&nbsp;</span>
                                <span class="entry-date">08 Nov 2012</span>
                                <span class="entry-meta">&nbsp;&nbsp;por&nbsp;</span>
                                <a href="#" class="entry-author">Admin</a>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum enim magna, in malesuada metus.</p>
                            </article>
                        </li>
                    </ul><!--older-posts-->
                    <div class="clear"></div>
                    <div class="divider"></div>
                </div><!--main-col-->
                <div class="clear"></div>
                
            </section><!--kopa-widget-->
            
            
            
            
            
             <section class="kopa-widget kp-carousel">
            
                <div class="kopa-widget-left clearfix">
                	<h3 class="widget-title">Programa</h3>
                    <a href="#" class="view-all">Veja nossos últimos programas</a>
                </div><!--kopa-widget-left-->
                
                <div class="main-col">
                
                    <div class="list-carousel responsive">
                        <ul class="recent-works3 clearfix">
                         
			<?php
				foreach($this->dadosProgramas as $key => $programa):
			?>
   
			 <li>
                                <article>
                                    <div class="article-thumb border-img">                                        
                                        <iframe width="300" height="315" src="http://www.youtube.com/embed/<?php echo $programa['url'];?>?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
                                    </div><!--article-thumb-->
                                    <a class="entry-title" href="#"><?php echo ucwords($programa['titulo'])?></a>
                                </article>
                            </li>
			<?php
				endforeach;
			?>
                            
                        </ul><!--end:recent-works-->
                        <div class="clear"></div>
                        <div class="carousel-nav clearfix">
                            <a id="prev-3" class="carousel-prev" href="#">&nbsp;</a>
                            <a id="next-3" class="carousel-next" href="#">&nbsp;</a>
                        </div><!--carousel-nav-->
                    </div><!--end:list-carousel-->
                    <div class="divider"></div>
                </div><!--main-col-->
                
                
                
                <div class="clear"></div>
            </section><!--kopa-widget-->
            
            
            
        </div><!--wrapper-->
    </div><!--main-content-->