<?php $this->doctype('HTML5')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=iso" />        
        <title>Casa Sul</title>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'./media/css/bootstrap.css')?>
        <style>
        </style>
    </head>
    
<!-- HEADER -->

<div class="page-header">
    <h1><img src = "<?php $this->baseUrl().'../public/media/img/logo.png'?>" width='5%' height='5%' alt = "" />
        <small>Administração de conteúdo</small></h1>
    
    <div id="area_login">
                <table>
                    <tr>
                        <td>Ola <b><?php $this->layout()->usuario->nome; ?> <i class="icon-user"></i> </b></td>
                        <td><a href="<?php echo $this->url(array("controller"=>"index"),null,true);?>">Logout</a></td>
                    </tr>
                </table>
            </div>
</div>
<!-- HEADER -->

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <!--Menu-->    
      <!-- <ul class="nav nav-list bs-docs-sidenav"> -->
          <ul class="nav nav-tabs nav-stacked bs-docs-sidenav affix">
          <li><a href="<?php $this->url(array("module"=>"admin","controller"=>"programas","action"=>"index"),null,true)?>">Programas</a></li>          
          <li><a href="<?php $this->url(array("module"=>"admin","controller"=>"midia","action"=>"index"),null,true)?>">Midia</a></li>          
          <?php if( $this->layout()->usuario->grupo == 1){?>
            <li><a>Administração</a></li>
            <li><a href="<?php $this->url(array("module"=>"admin","controller"=>"group","action"=>"index"),null,true)?>"><i class="icon-chevron-right"></i> Administrar Usuários</a></li>
            <li><a href="<?php $this->url(array("module"=>"admin","controller"=>"group","action"=>"new"),null,true)?>"><i class="icon-chevron-right"></i> Administrar grupos de usuários</a></li>
            <li><a href="<?php $this->url(array("module"=>"admin","controller"=>"responder","action"=>"index"),null,true)?>"><i class="icon-chevron-right"></i>Ver Respostas</a></li>
            <?php };?>
        </ul>
    </div>
    <div class="span8">
      <?php echo $this->layout()->content; ?>
    </div>
  </div><!-- div class=row -->
</div>