<?php
$dbImagens = new Application_Model_DbTable_Imagens();
$dbUsuario = new Admin_Model_DbTable_Usuario();
$usuario = $dbUsuario->pesquisarUsuario($this->noticia['autor']);

?>

<?php $imagem = $dbImagens->pesquisarImagem($this->noticia['thumb']);?>
    <center>
        <h1><?php echo $this->noticia['titulo']?></h1>
        <p><small>Resumo: <?php echo $this->noticia['descricao']?></small></p>
        <p><small>Autor:<?php echo $usuario['nome']?> Data de Publicação: <?php echo $this->noticia['dtInclusao']?></small></p>
        <br>
        <img src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php echo $this->noticia['titulo']?>">
        <div style="width:400px;word-wrap: break-word;text-align:justify;text-justify:inter-word;">
            <?php echo $this->noticia['texto']?>
        </div>
    </center>